proxmox_host                     = "100.0.0.100:8006"
proxmox_node_name                = "pve-01"
proxmox_api_user                 = "root@pam"
proxmox_api_password             = "password"
proxmox_insecure_skip_tls_verify = true

template_name        = "ubuntu-24-04"
template_description = "Ubuntu 24.04, generated by Packer"

ssh_username = "packer"
ssh_password = "packer"
# SHA-512 hash of the password "packer". Generate a replacement with:
#   mkpasswd -m sha-512 packer
#   openssl passwd -6 packer
ssh_password_hash = "$6$NSHPupATf1AA2kzE$ZeYuEX/nyLR3oezXDZT4msIjIg.Lt9oDOA/whGPr3KFiynLmiZfKC2KhLQK1X1xNhW4okFOippTK86.55H9yq1"

hostname = "ubuntu-24-04-cloudinit"
vmid     = 4000
locale   = "en_US"
timezone = "UTC"
cores    = 2
sockets  = 1
memory   = 4096
disk_size                = "20G"
datastore                = "local-lvm"
cloud_init_storage_pool  = "local-lvm"
network_bridge           = "vmbr0"
iso                      = "local:iso/ubuntu-24.04.3-live-server-amd64.iso"
